<a href="https://colab.research.google.com/github/RajanChoudhary09/custom-rnn-layer/blob/main/custom_RNN_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

class MyRNNCell(tf.keras.layers.Layer):
  def __init__(self, rnn_units, input_dim, output_dim):
    super(MyRNNCell, self).__init__()
    self.rnn_units = rnn_units
    self.input_dim = input_dim
    self.output_dim = output_dim

    self.W_xh = self.add_weight(shape=(self.rnn_units, self.input_dim), initializer='random_normal', trainable=True)
    self.W_hh = self.add_weight(shape=(self.rnn_units, self.rnn_units), initializer='random_normal', trainable=True)
    self.W_hy = self.add_weight(shape=(self.output_dim, self.rnn_units), initializer='random_normal', trainable=True)

    self.h = tf.zeros(shape=(self.rnn_units, 1))

  def call(self, x):
    self.h = tf.tanh(tf.matmul(self.W_xh, x) + tf.matmul(self.W_hh, self.h))
    output = tf.matmul(self.W_hy, self.h)
    return output, self.h

input_dim = 3
output_dim =2
rnn_units =4

rnn = MyRNNCell(rnn_units, input_dim, output_dim)

sequence_length = 5
inputs = [tf.random.normal(shape=(input_dim, 1)) for _ in range(sequence_length)]

print("Running the custom RNN on input sequence:\n")
for t, x in enumerate(inputs):
  output, hidden = rnn(x)
  print(f"Time step {t+1}:")
  print(f"Output shape: {output.shape}")
  print(f"Hidden state shape: {hidden.shape}")
  print("Input x:\n", x.numpy())
  print("Output y:\n", output.numpy())
  print("hidden state:\n", hidden.numpy())
  print("-" * 40)

Running the custom RNN on input sequence:

Time step 1:
Output shape: (2, 1)
Hidden state shape: (4, 1)
Input x:
 [[ 0.16834462]
 [-0.25420585]
 [ 0.13670385]]
Output y:
 [[0.00216748]
 [0.00400508]]
hidden state:
 [[-0.00618658]
 [ 0.03104162]
 [-0.00759619]
 [ 0.02321657]]
----------------------------------------
Time step 2:
Output shape: (2, 1)
Hidden state shape: (4, 1)
Input x:
 [[-0.2385381 ]
 [-0.12350856]
 [ 0.68320334]]
Output y:
 [[0.00723848]
 [0.00695001]]
hidden state:
 [[-0.0470682 ]
 [ 0.03454858]
 [ 0.00132556]
 [ 0.07259838]]
----------------------------------------
Time step 3:
Output shape: (2, 1)
Hidden state shape: (4, 1)
Input x:
 [[ 1.3462921]
 [-1.0266665]
 [ 0.2600799]]
Output y:
 [[0.00676842]
 [0.01719948]]
hidden state:
 [[ 0.00713515]
 [ 0.14478984]
 [-0.03788041]
 [ 0.08058292]]
----------------------------------------
Time step 4:
Output shape: (2, 1)
Hidden state shape: (4, 1)
Input x:
 [[ 0.46569976]
 [-0.82881016]
 [-0.42534247]]
Output y:
 [[-0.00083